import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css"
import { ReactQueryProvider } from "@/providers/react-query";
import { ToasterProvider } from "@/providers/sonner";
import SignUpModal from "@/modals/signUpModel";
import LoginModal from "@/modals/createAccountModal";
import LoginProvidersModal from "@/modals/loginProviderModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
<ReactQueryProvider>        
  <ToasterProvider>
  <SignUpModal/>
      <LoginModal/>
      <LoginProvidersModal/>
        {children}
        </ToasterProvider>      
</ReactQueryProvider>
        </body>

    </html>
  );
}
